language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requires.txt --use-mirrors
  - pip install coveralls --use-mirrors
# command to run tests
script:
  - nosetests --with-coverage --cover-package=mapequation
  #- coverage run --source=mapequation setup.py test
after_success:
  - coveralls