language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install:
  - pip install -r requires.txt --use-mirrors
  - pip install coveralls --use-mirrors
# command to run tests
script:
  - nosetests
  #- coverage run --source=pystratus setup.py test
#after_success:
#  - coveralls